### ISSUE TITLE
Create initial version 0.1.0 

### ISSUE THREAD

**Issue by nvdnkpr** [nvdnkpr/loopback-connector-arangodb#1]
Create initial version 0.1.0 supporting query, transactions, CRUD methods for documents, auto-migrate and auto-update

**Comment by mrbatista** [comment]
Hi @nvdnkpr,
I saw the [discussion](https://github.com/strongloop/loopback-connector/issues/19) about classes that loopback-connector-arangodb must extend (Connector or SQLConnector ). How will you proceed?
You want to wait improvement discussed in the thread or release the initial version?

**Comment by nvdnkpr** [comment]
Hi Matteo,
do you have time for a little planning session in order to create a backlog ?

I have a few ideas and I am looking forward to hear yours. I'll release the initial version then, so that we can then build an plan upon on it

**Comment by mrbatista** [comment]
Sure! Use the e-mail in my profile to ping me.

**Comment by mrbatista** [comment]
@nvdnkpr PING.

**Comment by mrbatista** [comment]
@nvdnkpr  I am waiting your answer in order to understand how I can contribuite to the development of the connector. I might work on the development of CRUD calls for edges.

**Comment by nvdnkpr** [comment]
Hello Mateo,
sorry I was in holidays and didn't have any access to a fast internet connection. Instead I had a few ideas. Do you have skype or anything ?

**Comment by mrbatista** [comment]
yes! skype: batistabomb87

**Comment by nvdnkpr** [comment]
Part of this issue:
#2 #4 #5 #6 #7

**Comment by mrbatista** [comment]
Landed via [8a1460f574](https://github.com/nvdnkpr/loopback-connector-arangodb/commit/8a1460f5749d7e3ea79b6ed7e8bcd69703d81243)
