### ISSUE TITLE
Rework 'UpdateOrCreate' method now with UPSERT available in Arango 2.6

### ISSUE THREAD

**Issue by nvdnkpr** [nvdnkpr/loopback-connector-arangodb#13]
The connector should be backwards compatible to ArangoDB 2.5

So in order to support Arango 2.5 and 2.6 there should be a version check
 - 2.5 (with no UPSERT command available) needs to execute two statements (UPDATE and CREATE as seperated statements) in a transaction
 - 2.6 (with the new UPSERT command) needs a normal AQL statement composed and executed

**Comment by mrbatista** [comment]
connector support version greater then 2.6.
Implemented via [8a1460f574](https://github.com/nvdnkpr/loopback-connector-arangodb/commit/8a1460f5749d7e3ea79b6ed7e8bcd69703d81243)
