### ISSUE TITLE
Provide access to the native driver

### ISSUE THREAD

**Issue by mrbatista** [nvdnkpr/loopback-connector-arangodb#2]
Provide access to the native driver for all functionality which aren't "out of the box".

**Comment by nvdnkpr** [comment]
Can you explain that a little bit more ?

**Comment by mrbatista** [comment]
like [this](https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js#L21), but at the moment I do not find the utility.

**Comment by nvdnkpr** [comment]
Ah, I see. It's basically the same as providing access to the query builder like in #6

**Comment by mrbatista** [comment]
you're right! just one line of code permit to use native driver for specific ArangoDB function.
For example:
1. [Managing AQL user functions](https://github.com/arangodb/arangojs#managing-aql-user-functions)
2. [Manipulating graphs](https://github.com/arangodb/arangojs#manipulating-graphs)
ecc...

Obviously use of these functions not permit change with others loopback connectors.

**Comment by mrbatista** [comment]
Implemented via [8a1460f574](https://github.com/nvdnkpr/loopback-connector-arangodb/commit/8a1460f5749d7e3ea79b6ed7e8bcd69703d81243)
