### ISSUE TITLE
Compatibility with Arangodb3?

### ISSUE THREAD

**Issue by rbrewer101** [nvdnkpr/loopback-connector-arangodb#30]
Hi Developers.

Any idea if this connector works with the newly released Arangodb v. 3?

**Comment by mrbatista** [comment]
Hi @rbrewer101, we plan to support arangoDB 3 in the near future. At the moment, the connector is tested only for arangoDB 2.x.x. Stay tuned!

**Comment by rbrewer101** [comment]
Great. Looking forward to it. Thanks for your work!
