### ISSUE TITLE
Support for custom queries

### ISSUE THREAD

**Issue by mrbatista** [nvdnkpr/loopback-connector-arangodb#5]
Loopback not support all ArangoDB operator.
Implement possibility to have access at custom function to compose complex queries (normal and graph queries).
Example for loopback-connector-mysql -> dataSource.connector.query(sql, [params], cb)

**Comment by nvdnkpr** [comment]
Hello Matteo,
The new version of the Loopback Arango Connector has [query](https://github.com/nvdnkpr/loopback-connector-arangodb/blob/feature-%231-InitialVersion/src/arango.coffee#L262) function and I modeled it after the signature that is used by the RBDMS connectors.

As for custom queries or functions I'm going to an extra issue for it, where the connector returns a fresh instance of the Arango Query Builder which I am already using in the connector.

**Comment by nvdnkpr** [comment]
Need to write tests for it

**Comment by mrbatista** [comment]
Implemented via [8a1460f574](https://github.com/nvdnkpr/loopback-connector-arangodb/commit/8a1460f5749d7e3ea79b6ed7e8bcd69703d81243)
