### ISSUE TITLE
Add method to get access to the Arango Query Builder

### ISSUE THREAD

**Issue by nvdnkpr** [nvdnkpr/loopback-connector-arangodb#6]
In order to use all built-in functions and also self-registered functions, we should add a method that returns the query builder, which is already in use for the other queries.

This should also enable "custom" queries as wished in #5

**Comment by nvdnkpr** [comment]
Are you okay with that issue ? ;)

**Comment by mrbatista** [comment]
Implemented via [8a1460f574](https://github.com/nvdnkpr/loopback-connector-arangodb/commit/8a1460f5749d7e3ea79b6ed7e8bcd69703d81243)
