### ISSUE TITLE
Write tests for 0.1.0

### ISSUE THREAD

**Issue by nvdnkpr** [nvdnkpr/loopback-connector-arangodb#7]
Write Tests
 - connection
 - CRUD methods
 - auto-migrate
 - auto-update

**Comment by mrbatista** [comment]
Data for tests: [Document](https://github.com/triAGENS/ArangoDB-Data/tree/master/Regions), [Geo](https://github.com/triAGENS/ArangoDB-Data/tree/master/Cities),

**Comment by nvdnkpr** [comment]
Close this issue due to the fact that writing test are dependent on the features that get implemented and therefore don't need an extra ticket
